### ISSUE TITLE
Need a dashboard

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#396]
We need a dashboard that walks our traces and produces the following things (daily):

- Number of jobs
- Length of each job running
- Spec of job (e.g. used GPU, amount of input data, amount of output data)
- Number of unique users submitting jobs
- Top users and jobs they submitted (in aggregate)
- Lots more... just start here :)

## Design

* Internal dashboard, no auth needed
* a 'unique user' is basically the public key used by the cli to submit job (find out more)

## Tasks

- [x] Get stuff working in local mode & stuffed with workarounds
- [x] [Add a Prometheus systemd unit to terraform scripts](https://github.com/filecoin-project/bacalhau/tree/main/ops/terraform)
- [x] [Configure Prometheus to push to Grafana Cloud](https://grafana.com/docs/grafana-cloud/data-configuration/metrics/metrics-prometheus/)
- [x] Add client-id to telemetry for `Number of unique users submitting jobs`
- [x] Redeploy Production
- [x] Configure dashboard(s) in Grafana 
   - [x] Connect data sources
   - [x] Aggregate data ([pending a Grafana support request re: cumulative sum](https://grafana.com/orgs/protocollabs/tickets/61348)) 

Follow up: implement more metrics ---> https://github.com/filecoin-project/bacalhau/issues/582

**Comment by lukemarsden** [comment]
Is this finished? Where's the dashboard?

**Comment by enricorotundo** [comment]
Waiting on PL infra team to provide us with a grafana cloud key. For some reason our (my & @aronchick ) accounts don't seem to be able to generate one. 

Code wise it's all set up. We may want to add new metrics tho.

**Comment by enricorotundo** [comment]
Public dasboard: https://protocollabs.grafana.net/public-dashboards/9fe7717277e540a7be88f1e8e8339bd8?orgId=1

**Comment by enricorotundo** [comment]
**Update:** still busy configuring the Grafana dashboard to display the actual total sum of the metrics. These are counters and they do reset every now and then, so a simple `sum` is not enough. The closest I got to achieving that is with this grafana query `last_over_time(sum(increase(jobs_received[10m]))[10m])`. WIP. Stay tuned

**Comment by enricorotundo** [comment]
Note Grafana cloud public dashboards have only alpha support - sometimes it's quite painful to have the public synced with the private dashboard :(
