### ISSUE TITLE
Add GPU capable demonstrator machines to production network

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#423]
**Use Case**

As a user of the public Bacalhau network, I want to be able to schedule and run GPU jobs.

**Tasks**

* [x] Develop Terraform code to create GPU machines in dev environment, then disable
* [x] Update and release production code
* [x] Record demo of a GPU workload using the production network, upload to docs/youtube

**Details**

* Machine: 1x [NVidia T4](https://www.nvidia.com/en-us/data-center/tesla-t4/), 4cpu, 16GB ram (`e2-standard-4` equivalent). The T4 costs $0.35 per hour and is the cheapest GPU available. It has 16GB of vRAM, which is similar to machines that exist within the IPFS network.
* Add 1x of these machines to production only.

**Caveats**

* Compared to common IPFS node specifications, the GPUs available in GCP (and AWS) are of a different architecture. We assume that Docker's GPU implementation works with all GPU types in a similar way to the T4.

**Comment by lukemarsden** [comment]
Sounds great! Maybe we only need one in prod.

**Comment by philwinder** [comment]
Closed with https://github.com/filecoin-project/bacalhau/commit/b797491bed7f0ce503a4309b1f8018edc4f6ae33
