### ISSUE TITLE
Examples Epic

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#538]
- [ ] Cleanup/update stale examples (there’re some in the examples/ folder)

Need real world examples for Bacalhau - each one should have:
- Real world scenario - e.g. "What can you do with Bacalhau that you can't do today?"
- Docs (published)
- Test Suite/integration test
- Use as few flags as possible (use defaults)

Vedant [started work](https://docs.google.com/document/d/15PiCoEwy5r4oHuPya3RJApGzmFcRZH7rOq_xKB0pKxM/edit#heading=h.duoqy6w9snh6) on some of these:

Examples to work on (some random thoughtS):
- [ ] Stable diffusion
    - [ ] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] YOLO
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Consuming blockchain data and producing an output
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Large number of image processing
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Expanding a very large file, breaking it up into smaller files and storing the smaller files as a single CID in IPFS
    - [ ] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Breaking down a very large file for embarrassingly execution (arrow? materialize?)
    - [ ] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Python in a docker container - Do this with loading a python script from github using -u
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Matlab in a docker container (Matlab docker requires license)
- [ ] Trivial example of running R in a docker container
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Numpy in a docker container
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Pandas in a docker container
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Tensorflow in a docker container
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Pytorch in a docker container
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Sklearn in a docker container
    - [x] Command
    - [ ] Docs
    - [ ]  Tests
- [ ] Trivial example of running Spark local in a docker container (maybe not - reported issues doing this?)
- [ ] Trivial example of running an entire Airflow job in Airflow local in a docker container
- [ ] Trivial example of running duckdb in a docker container 
(https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1660234712911259)
    - [x] Command
    - [ ] Docs
    - [ ]  Tests

Ideally, each test should have a full integration suite. E.g.
- Each example should be a new integration test, that runs nightly on CICD
- Each example should have a documentation page - like this https://docs.bacalhau.org/demos/image-processing
- Each example should consume a 1 KB file from IPFS (already uploaded) and produce an output
- The integration test should look at the stdout, stderr, and the get result

**Comment by enricorotundo** [comment]
Moved `examples/` to dedicated repo: https://github.com/bacalhau-project/examples

**Comment by philwinder** [comment]
Thanks for all the ideas guys. We've captured them in a spreadsheet and will be working on them one at a time, with an issue for each one.

https://docs.google.com/spreadsheets/d/1QwOAYlFOpoJbWAGs5W1KdctDUouKOwLzxgTyAhyHD6Q/edit?pli=1#gid=0
