### ISSUE TITLE
Caltech - Benchmarking

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#547]
**Tasks**

- [ ] ~Spin up OVH infra using terraform, see Slack #bacalhau-caltech-workloads, store in ops directory~
  - ~Using HGR-HCI-5 machines in Oregon is fine: https://us.ovhcloud.com/bare-metal/high-grade/hgr-hci-5/ . They prefer 20GB of storage available per thread, but not critical for the benchmarks~
- [ ] ~Install bacalhau, connect to the production network, test~
- [ ] ~Check the benchmark tools, will they work in docker/bacalhau?~
  - https://w3.hepix.org/benchmarking/how_to_run_hs06.html
  - https://www.spec.org/cpu2017/
- [ ] ~Run benchmark job in bacalhau, report results, figure out what to do next~

**Comment by enricorotundo** [comment]
We successfully run the following benchmark: https://github.com/cmscaltech/docker-hs06/tree/master/hepscore

Next step should be https://github.com/filecoin-project/bacalhau/issues/620.
