### ISSUE TITLE
UX improvements, bugfixes, docs etc

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#661]
- [x] https://github.com/filecoin-project/bacalhau/pull/601 - includes 2k of stdout/stderr in describe output
- [x] https://github.com/filecoin-project/bacalhau/issues/611
- [x] https://github.com/filecoin-project/bacalhau/issues/624
- [x] Progress bars!
- [-] Streaming logs! See https://github.com/filecoin-project/bacalhau/issues/448

**Comment by philwinder** [comment]
Stale. Last remaining issue is covered by another bigger issue.
