### ISSUE TITLE
Clean up CLI

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#707]
- [x] Errors should friendly print (no direct zerolog output)
- [x] Errors from backend shouldn't be 500s
- [ ] Restructure flags so humans aren't scared off (kubectl isn't bad here)
- [x] Stdin from create
- [x] Stdin from validate
- [x] Stdin from elsewhere?
- [x] More?

**Comment by aronchick** [comment]
stdin from create and validate are done - others?
